### ISSUE TITLE
Copy-Paste focuses on wrong input

### ISSUE THREAD

**Issue by kamnakis** [dammy001/vue-split-input#56]
After I paste a text into the input, it focuses on the second from the end input. Shouldn't it focus on the last?

Also if I paste from android typehint (keybord suggestions) it only pastes the first letter.

Reproduction:
https://github.com/kamnakis/vue-split-input-test

**Comment by dammy001** [comment]
@kamnakis Will check this issue and fix. Thanks.

**Comment by dammy001** [comment]
issue fixed here #82
